### ISSUE TITLE
Error unittouu Attribute

### ISSUE THREAD

**Issue by Malsasa** [Florianjw/NiceCharts#5]
My friends tried NiceCharts in Linux and they got this error message:

Log:
Traceback (most recent call last):
File "nicechart.py", line 579, in <module>
effect.affect()
File "/usr/share/inkscape/extensions/inkex.py", line 268, in affect
self.effect()
File "nicechart.py", line 186, in effect
width = inkex.unittouu(svg.get('width'))
AttributeError: 'module' object has no attribute 'unittouu'

Inkscape 0.48.4, Python 2.7.8, source code from https://launchpad.net/nicecharts. The error was same, around of *inkex.py* and *unitouu* attribute. Please tell me if my information is not enough.

**Comment by Florianjw** [comment]
Oh dear, I participated in the creation of this script four years ago and by the standards I apply today it really isn't nice and I have very little python-experience.

For a start: I can reproduce the error, so what you have given me should be sufficient. I'll see that I'll get that fixed, but please understand that I cannot make any promises.

**Comment by Florianjw** [comment]
Okay, luckily this was a really simple fix, it should work now: https://github.com/Florianjw/NiceCharts/commit/f5da35d9ee608a930e686ce4e09d3ad88dbbf102

If the problem persists, please reopen.
